# Generated by Django 3.0.2 on 2020-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myth',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
